### ISSUE TITLE
Interactive Map support for Daisy Chain Buildings

### ISSUE THREAD

**Issue by samuelcanadi** [DellAquila/DaisyChainPowerCables#2]
It would be great if the interactive map could handle daisy chain buildings correctly in uploades save files. Would it be possible to get that working?

**Comment by JsGarneau** [comment]
@DellAquila I would really like this to happen, I offer you my help to check this out. I only need your approbation so I can contact SCMI owner and he'll hopefully allow me access to their repo.

**Comment by DellAquila** [comment]
That would be Awesome Jean!! :) I really hope it works out...

Em qui., 7 de jan. de 2021 às 09:57, Jean-Simon Garneau <
notifications@github.com> escreveu:

**Comment by AnthorNet** [comment]
Hey @DellAquila if you register on SCIM, I can give you modder access and you'll get access to the modder backend where you can add all your mods on a simple way ;)

**Comment by DellAquila** [comment]
Thanks Anthor!! Im there with the email celaquila@gmail.com

**Comment by samuelcanadi** [comment]
Glad it worked out :)
